"""
FormKit Optimizer — Multi-Period Formwork Kit Optimization Engine
================================================================

This module implements the core MIP (Mixed-Integer Programming) formulation
for optimizing formwork kitting across a multi-period pour schedule.

Solver: Google OR-Tools CP-SAT (primary) / HiGHS via highspy (fallback)

The formulation minimizes total formwork cost across the project by jointly
optimizing:
  - Kit configuration selection per pour
  - Component-to-pour assignment with reuse tracking
  - Procurement vs. rental decisions
  - Multi-period inventory balance

Domain: Construction formwork planning for multi-storey residential towers.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import date, timedelta
from enum import Enum
from typing import Optional

from ortools.sat.python import cp_model

logger = logging.getLogger(__name__)


# ============================================================
# DATA CLASSES — Typed inputs to the optimizer
# ============================================================

class ComponentType(Enum):
    PANEL = "PANEL"
    FILLER = "FILLER"
    TIE_ROD = "TIE_ROD"
    TIE_CONE = "TIE_CONE"
    WALER = "WALER"
    PROP = "PROP"
    CLAMP = "CLAMP"
    WEDGE = "WEDGE"
    CORNER = "CORNER"
    ACCESSORY = "ACCESSORY"


class PourType(Enum):
    WALL = "WALL"
    SLAB = "SLAB"
    COLUMN = "COLUMN"
    BEAM = "BEAM"
    SHEAR_WALL = "SHEAR_WALL"


@dataclass
class Component:
    """A formwork component type (not a physical instance)."""
    component_id: str
    system_code: str
    component_type: ComponentType
    description: str
    width_mm: Optional[int] = None
    height_mm: Optional[int] = None
    weight_kg: float = 0.0
    unit_cost_buy: float = 0.0
    unit_cost_rent_per_day: float = 0.0
    loss_rate_per_cycle: float = 0.002
    damage_rate_per_cycle: float = 0.005
    rated_reuse_cycles: int = 300


@dataclass
class CompatibilityRule:
    """Defines quantity ratio between components (e.g., ties per panel)."""
    source_component_id: str
    target_component_id: str
    quantity_ratio: float  # target_qty = source_qty * ratio
    notes: str = ""


@dataclass
class KitConfig:
    """A candidate kit configuration for a specific pour.
    
    Generated by the Panel Layout Engine before optimization.
    Each pour typically has 2-5 candidate configs.
    """
    config_id: str
    pour_id: str
    component_demands: dict[str, int]  # component_id -> quantity needed
    total_panel_area_m2: float
    coverage_ratio: float
    estimated_handling_cost: float  # assembly + strip labor
    description: str = ""


@dataclass
class Pour:
    """A concrete pour event with schedule and formwork demand."""
    pour_id: str
    tower_code: str
    floor_number: int
    zone_code: str
    pour_type: PourType
    planned_date: date
    net_surface_area_m2: float
    concrete_grade: str
    strip_cycle_hours: int
    assigned_system_code: str
    candidate_configs: list[KitConfig] = field(default_factory=list)
    is_locked: bool = False          # planner has locked this pour's kit
    locked_config_id: str | None = None

    @property
    def strip_date(self) -> date:
        """Earliest date formwork can be stripped."""
        strip_days = max(1, self.strip_cycle_hours // 24)
        return self.planned_date + timedelta(days=strip_days)

    @property
    def available_date(self) -> date:
        """Date stripped components are cleaned and available for reuse.
        Assumes 0.5-day cleaning buffer after stripping."""
        return self.strip_date + timedelta(days=1)

    @property
    def erection_start_date(self) -> date:
        """Formwork erection starts 1 day before pour."""
        return self.planned_date - timedelta(days=1)


@dataclass
class InventoryPosition:
    """Current inventory of a component type at optimization start."""
    component_id: str
    qty_available: int
    qty_deployed: int  # will become available per deployed_pour schedule
    avg_remaining_cycles: float


@dataclass
class DeployedAllocation:
    """Components currently deployed on an active pour (not yet stripped)."""
    component_id: str
    pour_id: str
    quantity: int
    expected_available_date: date


# ============================================================
# OPTIMIZER RESULT TYPES
# ============================================================

@dataclass
class KitAssignment:
    """Result: which kit config was selected and how components are sourced."""
    pour_id: str
    selected_config_id: str
    component_assignments: list[ComponentAssignment]
    total_cost: float
    explanation: str


@dataclass
class ComponentAssignment:
    """Result: sourcing detail for one component in a kit."""
    component_id: str
    quantity: int
    source: str  # "INVENTORY", "REUSE_FROM:<pour_id>", "PROCURE", "RENT"
    available_from: date
    cost: float
    reason: str  # human-readable explanation


@dataclass
class ProcurementPlan:
    """Result: what to buy or rent, and when."""
    component_id: str
    quantity: int
    action: str  # "BUY" or "RENT"
    needed_by: date
    cost: float
    justification: str


@dataclass
class OptimizationResult:
    """Complete output of an optimization run."""
    run_id: str
    project_id: str
    status: str  # "OPTIMAL", "FEASIBLE", "INFEASIBLE", "TIMEOUT"
    objective_value: float
    solve_time_seconds: float
    optimality_gap: float
    kit_assignments: list[KitAssignment]
    procurement_plan: list[ProcurementPlan]
    inventory_trajectory: dict[str, list[tuple[date, int]]]  # component_id -> [(date, qty_available)]
    total_cost_breakdown: dict[str, float]


# ============================================================
# PANEL LAYOUT ENGINE
# ============================================================

class PanelLayoutEngine:
    """Generates candidate kit configurations for a pour.
    
    Given a pour's surface area and the assigned formwork system,
    produces 2-5 feasible panel arrangements with varying trade-offs
    between large panels (less handling) and small panels (more flexibility).
    """

    # Standard PERI TRIO panel widths in mm, ordered descending
    TRIO_WIDTHS = [2400, 1200, 900, 600, 450, 330, 240]
    TRIO_FILLERS = [150, 100, 50]

    def __init__(self, components: list[Component], rules: list[CompatibilityRule]):
        self.components = {c.component_id: c for c in components}
        self.components_by_system: dict[str, list[Component]] = {}
        for c in components:
            self.components_by_system.setdefault(c.system_code, []).append(c)
        self.rules = rules

    def generate_configs(self, pour: Pour, max_configs: int = 3) -> list[KitConfig]:
        """Generate candidate kit configurations for a pour."""
        if pour.pour_type == PourType.WALL:
            return self._generate_wall_configs(pour, max_configs)
        elif pour.pour_type == PourType.SLAB:
            return self._generate_slab_configs(pour, max_configs)
        else:
            # Column, beam — simplified single-config
            return self._generate_simple_config(pour)

    def _generate_wall_configs(self, pour: Pour, max_configs: int) -> list[KitConfig]:
        """Generate wall kit configurations.
        
        Assumes wall formwork is applied to BOTH faces.
        Wall length derived from surface area / (2 * wall height).
        """
        system_code = pour.assigned_system_code
        panels = [c for c in self.components_by_system.get(system_code, [])
                  if c.component_type == ComponentType.PANEL]
        if not panels:
            logger.warning(f"No panels found for system {system_code}")
            return []

        # Derive wall dimensions (both faces)
        wall_height_m = 2.7  # default TRIO height
        total_length_m = pour.net_surface_area_m2 / wall_height_m  # both faces combined
        single_face_length_mm = int((total_length_m / 2) * 1000)

        configs = []
        strategies = [
            ("MAX_LARGE", "Maximize large panels — fewer pieces, less handling"),
            ("BALANCED", "Balanced mix — moderate handling, good reuse flexibility"),
            ("MAX_FLEXIBLE", "Maximum flexibility — smaller panels, easier redistribution"),
        ]

        for idx, (strategy_name, desc) in enumerate(strategies[:max_configs]):
            demands = self._layout_panels_for_wall(
                single_face_length_mm, system_code, strategy_name, panels
            )
            # Double for both faces
            for comp_id in list(demands.keys()):
                comp = self.components.get(comp_id)
                if comp and comp.component_type == ComponentType.PANEL:
                    demands[comp_id] *= 2

            # Add accessories via compatibility rules
            demands = self._add_accessories(demands, system_code)

            total_panel_area = sum(
                (self.components[cid].width_mm or 0) * (self.components[cid].height_mm or 0) / 1e6 * qty
                for cid, qty in demands.items()
                if self.components.get(cid) and self.components[cid].component_type == ComponentType.PANEL
            )

            handling_cost = sum(
                qty * self.components[cid].weight_kg * 0.5  # ₹0.5 per kg handling estimate
                for cid, qty in demands.items()
                if cid in self.components
            )

            config = KitConfig(
                config_id=f"{pour.pour_id}-CFG-{chr(65 + idx)}",
                pour_id=pour.pour_id,
                component_demands=demands,
                total_panel_area_m2=total_panel_area,
                coverage_ratio=total_panel_area / pour.net_surface_area_m2 if pour.net_surface_area_m2 > 0 else 0,
                estimated_handling_cost=handling_cost,
                description=desc,
            )
            configs.append(config)

        return configs

    def _layout_panels_for_wall(
        self, length_mm: int, system_code: str, strategy: str,
        panels: list[Component]
    ) -> dict[str, int]:
        """Bin-packing panels to cover a wall face of given length.
        
        Strategy controls which panel sizes are preferred:
        - MAX_LARGE: Start with largest panels
        - BALANCED: Mix of large and medium
        - MAX_FLEXIBLE: Prefer smaller, more numerous panels
        """
        available_widths = sorted(
            [(p.width_mm, p.component_id) for p in panels if p.width_mm],
            key=lambda x: x[0], reverse=True
        )

        if strategy == "MAX_FLEXIBLE":
            # Skip the largest panel size
            if len(available_widths) > 1:
                available_widths = available_widths[1:]
        elif strategy == "BALANCED":
            # Start with second-largest
            if len(available_widths) > 2:
                available_widths = available_widths[1:]

        demands: dict[str, int] = {}
        remaining = length_mm

        for width, comp_id in available_widths:
            if remaining <= 0:
                break
            count = remaining // width
            if count > 0:
                demands[comp_id] = count
                remaining -= count * width

        # Fill remainder with fillers
        if remaining > 0:
            fillers = [c for c in self.components_by_system.get(system_code, [])
                       if c.component_type == ComponentType.FILLER]
            filler_widths = sorted(
                [(f.width_mm, f.component_id) for f in fillers if f.width_mm],
                key=lambda x: x[0], reverse=True
            )
            for fw, fid in filler_widths:
                if remaining <= 0:
                    break
                fcount = remaining // fw
                if fcount > 0:
                    demands[fid] = fcount
                    remaining -= fcount * fw

        return demands

    def _generate_slab_configs(self, pour: Pour, max_configs: int) -> list[KitConfig]:
        """Simplified slab config — area-based panel count + props."""
        system_code = pour.assigned_system_code or "PERI_GRIDFLEX"
        panels = [c for c in self.components_by_system.get(system_code, [])
                  if c.component_type == ComponentType.PANEL]
        props = [c for c in self.components_by_system.get(system_code, [])
                 if c.component_type == ComponentType.PROP]

        if not panels:
            return self._generate_simple_config(pour)

        # Pick the largest panel
        panel = max(panels, key=lambda p: (p.width_mm or 0) * (p.height_mm or 0))
        panel_area = ((panel.width_mm or 0) * (panel.height_mm or 0)) / 1e6
        if panel_area <= 0:
            return self._generate_simple_config(pour)

        num_panels = int(pour.net_surface_area_m2 / panel_area) + 1
        # Props: 1 per 2m² of slab area
        num_props = int(pour.net_surface_area_m2 / 2.0) + 1

        demands = {panel.component_id: num_panels}
        if props:
            demands[props[0].component_id] = num_props

        config = KitConfig(
            config_id=f"{pour.pour_id}-CFG-A",
            pour_id=pour.pour_id,
            component_demands=demands,
            total_panel_area_m2=num_panels * panel_area,
            coverage_ratio=(num_panels * panel_area) / pour.net_surface_area_m2,
            estimated_handling_cost=num_panels * (panel.weight_kg * 0.5),
            description="Standard slab panel coverage with props",
        )
        return [config]

    def _generate_simple_config(self, pour: Pour) -> list[KitConfig]:
        """Fallback: generate a placeholder config based on surface area."""
        return [KitConfig(
            config_id=f"{pour.pour_id}-CFG-A",
            pour_id=pour.pour_id,
            component_demands={},
            total_panel_area_m2=pour.net_surface_area_m2,
            coverage_ratio=1.0,
            estimated_handling_cost=pour.net_surface_area_m2 * 50,
            description="Placeholder — requires manual component specification",
        )]

    def _add_accessories(self, demands: dict[str, int], system_code: str) -> dict[str, int]:
        """Apply compatibility rules to add tie rods, cones, clamps, etc."""
        added: dict[str, int] = {}
        for rule in self.rules:
            if rule.source_component_id in demands and rule.quantity_ratio:
                source_qty = demands[rule.source_component_id]
                target_qty = max(1, int(source_qty * rule.quantity_ratio))
                added[rule.target_component_id] = (
                    added.get(rule.target_component_id, 0) + target_qty
                )
        # Merge
        result = dict(demands)
        for comp_id, qty in added.items():
            result[comp_id] = result.get(comp_id, 0) + qty
        return result


# ============================================================
# MULTI-PERIOD OPTIMIZER (CP-SAT FORMULATION)
# ============================================================

class FormworkOptimizer:
    """Multi-period formwork kit optimizer using CP-SAT.
    
    Solves the joint problem of:
    1. Kit configuration selection per pour
    2. Component assignment (inventory reuse vs. new procurement vs. rental)
    3. Multi-period inventory balance across all time periods
    
    Objective: Minimize total project formwork cost.
    """

    # Cost scaling factor (CP-SAT works with integers)
    COST_SCALE = 100  # Store costs in paise (1/100 of rupee)

    def __init__(
        self,
        pours: list[Pour],
        components: list[Component],
        initial_inventory: list[InventoryPosition],
        deployed_allocations: list[DeployedAllocation],
        handling_cost_per_kg: float = 0.5,
        holding_cost_per_unit_per_day: float = 2.0,
        max_solve_time_seconds: int = 300,
    ):
        self.pours = sorted(pours, key=lambda p: p.planned_date)
        self.components = {c.component_id: c for c in components}
        self.initial_inventory = {ip.component_id: ip for ip in initial_inventory}
        self.deployed = deployed_allocations
        self.handling_cost_per_kg = handling_cost_per_kg
        self.holding_cost_per_unit_per_day = holding_cost_per_unit_per_day
        self.max_solve_time = max_solve_time_seconds

        # Build time index
        self._build_time_index()

    def _build_time_index(self):
        """Map pours and dates to integer time periods."""
        all_dates = set()
        for p in self.pours:
            all_dates.add(p.erection_start_date)
            all_dates.add(p.planned_date)
            all_dates.add(p.strip_date)
            all_dates.add(p.available_date)
        for da in self.deployed:
            all_dates.add(da.expected_available_date)

        self.date_list = sorted(all_dates)
        self.date_to_period = {d: i for i, d in enumerate(self.date_list)}
        self.num_periods = len(self.date_list)

    def solve(self) -> OptimizationResult:
        """Build and solve the MIP model. Returns OptimizationResult."""
        run_id = str(uuid.uuid4())
        model = cp_model.CpModel()

        # Shorthand
        pours = self.pours
        comp_ids = list(self.components.keys())
        n_pours = len(pours)
        n_comps = len(comp_ids)

        logger.info(f"Building model: {n_pours} pours, {n_comps} component types, {self.num_periods} periods")

        # ============================================================
        # DECISION VARIABLES
        # ============================================================

        # z[p][k] = 1 if kit config k is selected for pour p
        z: dict[int, dict[str, object]] = {}
        for pi, pour in enumerate(pours):
            if pour.is_locked and pour.locked_config_id:
                # Locked — no choice variable needed
                z[pi] = {}
                continue
            z[pi] = {}
            for config in pour.candidate_configs:
                z[pi][config.config_id] = model.NewBoolVar(f"z_{pi}_{config.config_id}")

        # x[p][c] = quantity of component c assigned to pour p
        x: dict[int, dict[str, object]] = {}
        for pi, pour in enumerate(pours):
            x[pi] = {}
            for cid in comp_ids:
                max_demand = max(
                    (cfg.component_demands.get(cid, 0) for cfg in pour.candidate_configs),
                    default=0
                )
                if max_demand > 0:
                    x[pi][cid] = model.NewIntVar(0, max_demand * 2, f"x_{pi}_{cid}")

        # b[c][t] = new procurement of component c at time period t
        b: dict[str, dict[int, object]] = {}
        for cid in comp_ids:
            b[cid] = {}
            for t in range(self.num_periods):
                b[cid][t] = model.NewIntVar(0, 500, f"b_{cid}_{t}")

        # r[c][t] = rental quantity of component c active at time period t
        r: dict[str, dict[int, object]] = {}
        for cid in comp_ids:
            r[cid] = {}
            for t in range(self.num_periods):
                r[cid][t] = model.NewIntVar(0, 200, f"r_{cid}_{t}")

        # I[c][t] = idle inventory of component c at end of period t
        inv: dict[str, dict[int, object]] = {}
        for cid in comp_ids:
            inv[cid] = {}
            for t in range(self.num_periods):
                inv[cid][t] = model.NewIntVar(0, 1000, f"I_{cid}_{t}")

        # ============================================================
        # CONSTRAINTS
        # ============================================================

        # C1 + C2: Kit config selection — exactly one per pour
        for pi, pour in enumerate(pours):
            if pour.is_locked:
                continue
            if not pour.candidate_configs:
                continue
            model.AddExactlyOne(list(z[pi].values()))

        # Link x[p][c] to selected config's demand
        for pi, pour in enumerate(pours):
            if pour.is_locked and pour.locked_config_id:
                # Fixed assignment
                locked_cfg = next(
                    (cfg for cfg in pour.candidate_configs if cfg.config_id == pour.locked_config_id),
                    None
                )
                if locked_cfg:
                    for cid, qty in locked_cfg.component_demands.items():
                        if cid in x[pi]:
                            model.Add(x[pi][cid] == qty)
                continue

            for cid in comp_ids:
                if cid not in x[pi]:
                    continue
                # x[p][c] must equal the demand of the selected config
                for config in pour.candidate_configs:
                    demand = config.component_demands.get(cid, 0)
                    if config.config_id in z[pi]:
                        # If this config is selected, x must >= demand
                        model.Add(
                            x[pi][cid] >= demand
                        ).OnlyEnforceIf(z[pi][config.config_id])
                        model.Add(
                            x[pi][cid] <= demand
                        ).OnlyEnforceIf(z[pi][config.config_id])

        # C3: Inventory balance across periods
        for cid in comp_ids:
            for t in range(self.num_periods):
                current_date = self.date_list[t]

                # Components returning from deployed pours on this date
                returning = 0
                for da in self.deployed:
                    if da.component_id == cid and da.expected_available_date == current_date:
                        returning += da.quantity

                # Components returning from optimizer-assigned pours stripping on this date
                returning_from_pours = []
                for pi, pour in enumerate(pours):
                    if pour.available_date == current_date and cid in x[pi]:
                        returning_from_pours.append(x[pi][cid])

                # Components deployed to pours starting erection on this date
                deploying_to_pours = []
                for pi, pour in enumerate(pours):
                    if pour.erection_start_date == current_date and cid in x[pi]:
                        deploying_to_pours.append(x[pi][cid])

                if t == 0:
                    initial_qty = self.initial_inventory.get(cid, InventoryPosition(cid, 0, 0, 0)).qty_available
                    # I[c][0] = initial + bought + rented + returning - deployed
                    terms_plus = [b[cid][t], r[cid][t]]
                    terms_minus = deploying_to_pours

                    model.Add(
                        inv[cid][t]
                        == initial_qty + returning
                        + sum(1 * v for v in terms_plus)
                        + sum(1 * v for v in returning_from_pours)
                        - sum(1 * v for v in terms_minus)
                    )
                else:
                    model.Add(
                        inv[cid][t]
                        == inv[cid][t - 1] + returning
                        + b[cid][t] + r[cid][t]
                        + sum(1 * v for v in returning_from_pours)
                        - sum(1 * v for v in deploying_to_pours)
                    )

                # Non-negative inventory (already enforced by variable bounds, but explicit)
                model.Add(inv[cid][t] >= 0)

        # ============================================================
        # OBJECTIVE FUNCTION
        # ============================================================
        cost_terms = []
        S = self.COST_SCALE

        for cid in comp_ids:
            comp = self.components[cid]

            for t in range(self.num_periods):
                # Procurement cost
                buy_cost = int(comp.unit_cost_buy * S)
                if buy_cost > 0:
                    cost_terms.append(buy_cost * b[cid][t])

                # Rental cost (per day — approximate by period length)
                rent_cost = int(comp.unit_cost_rent_per_day * S)
                if rent_cost > 0:
                    cost_terms.append(rent_cost * r[cid][t])

                # Holding cost for idle inventory
                hold_cost = int(self.holding_cost_per_unit_per_day * S)
                cost_terms.append(hold_cost * inv[cid][t])

        # Handling cost per pour (based on assigned quantities)
        for pi, pour in enumerate(pours):
            for cid in x[pi]:
                comp = self.components.get(cid)
                if comp:
                    handle_cost = int(comp.weight_kg * self.handling_cost_per_kg * S)
                    if handle_cost > 0:
                        cost_terms.append(handle_cost * x[pi][cid])

        # Loss cost (expected loss per cycle)
        for pi, pour in enumerate(pours):
            for cid in x[pi]:
                comp = self.components.get(cid)
                if comp and comp.loss_rate_per_cycle > 0:
                    loss_cost = int(comp.loss_rate_per_cycle * comp.unit_cost_buy * S)
                    if loss_cost > 0:
                        cost_terms.append(loss_cost * x[pi][cid])

        model.Minimize(sum(cost_terms))

        # ============================================================
        # SOLVE
        # ============================================================
        solver = cp_model.CpSolver()
        solver.parameters.max_time_in_seconds = self.max_solve_time
        solver.parameters.num_workers = 4
        solver.parameters.log_search_progress = True

        logger.info("Starting CP-SAT solve...")
        status = solver.Solve(model)

        status_map = {
            cp_model.OPTIMAL: "OPTIMAL",
            cp_model.FEASIBLE: "FEASIBLE",
            cp_model.INFEASIBLE: "INFEASIBLE",
            cp_model.MODEL_INVALID: "INFEASIBLE",
            cp_model.UNKNOWN: "TIMEOUT",
        }
        result_status = status_map.get(status, "TIMEOUT")

        logger.info(f"Solve status: {result_status}, time: {solver.WallTime():.1f}s")

        if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            return OptimizationResult(
                run_id=run_id,
                project_id="",
                status=result_status,
                objective_value=0,
                solve_time_seconds=solver.WallTime(),
                optimality_gap=1.0,
                kit_assignments=[],
                procurement_plan=[],
                inventory_trajectory={},
                total_cost_breakdown={},
            )

        # ============================================================
        # EXTRACT SOLUTION
        # ============================================================
        kit_assignments = []
        procurement_plan = []
        total_procurement = 0.0
        total_rental = 0.0
        total_handling = 0.0
        total_holding = 0.0
        total_loss = 0.0

        for pi, pour in enumerate(pours):
            # Determine selected config
            selected_config = None
            if pour.is_locked and pour.locked_config_id:
                selected_config = next(
                    (cfg for cfg in pour.candidate_configs if cfg.config_id == pour.locked_config_id),
                    None
                )
            else:
                for config in pour.candidate_configs:
                    if config.config_id in z[pi] and solver.Value(z[pi][config.config_id]) == 1:
                        selected_config = config
                        break

            if not selected_config:
                continue

            # Build component assignments
            comp_assignments = []
            for cid, var in x[pi].items():
                qty = solver.Value(var)
                if qty <= 0:
                    continue

                comp = self.components.get(cid)
                if not comp:
                    continue

                # Determine source (simplified heuristic for solution extraction)
                # In production, track reuse flows explicitly via y variables
                source = "INVENTORY"
                reason = f"{comp.description} (qty: {qty}) — Assigned from available inventory."

                comp_assignments.append(ComponentAssignment(
                    component_id=cid,
                    quantity=qty,
                    source=source,
                    available_from=pour.erection_start_date,
                    cost=qty * comp.unit_cost_buy * comp.loss_rate_per_cycle + qty * comp.weight_kg * self.handling_cost_per_kg,
                    reason=reason,
                ))

            kit_assignments.append(KitAssignment(
                pour_id=pour.pour_id,
                selected_config_id=selected_config.config_id,
                component_assignments=comp_assignments,
                total_cost=sum(ca.cost for ca in comp_assignments),
                explanation=f"Config '{selected_config.description}' selected. Coverage: {selected_config.coverage_ratio:.2f}x.",
            ))

        # Extract procurement plan
        for cid in comp_ids:
            comp = self.components.get(cid)
            if not comp:
                continue
            for t in range(self.num_periods):
                buy_qty = solver.Value(b[cid][t])
                if buy_qty > 0:
                    cost = buy_qty * comp.unit_cost_buy
                    total_procurement += cost
                    procurement_plan.append(ProcurementPlan(
                        component_id=cid,
                        quantity=buy_qty,
                        action="BUY",
                        needed_by=self.date_list[t],
                        cost=cost,
                        justification=f"Procure {buy_qty}x {comp.description} by {self.date_list[t]} — insufficient inventory/reuse to cover demand.",
                    ))

                rent_qty = solver.Value(r[cid][t])
                if rent_qty > 0:
                    cost = rent_qty * comp.unit_cost_rent_per_day
                    total_rental += cost
                    procurement_plan.append(ProcurementPlan(
                        component_id=cid,
                        quantity=rent_qty,
                        action="RENT",
                        needed_by=self.date_list[t],
                        cost=cost,
                        justification=f"Rent {rent_qty}x {comp.description} for period starting {self.date_list[t]} — purchase not justified for remaining reuse.",
                    ))

        # Build inventory trajectory
        inventory_trajectory: dict[str, list[tuple[date, int]]] = {}
        for cid in comp_ids:
            trajectory = []
            for t in range(self.num_periods):
                qty = solver.Value(inv[cid][t])
                trajectory.append((self.date_list[t], qty))
            if any(qty > 0 for _, qty in trajectory):
                inventory_trajectory[cid] = trajectory

        objective_value = solver.ObjectiveValue() / self.COST_SCALE

        return OptimizationResult(
            run_id=run_id,
            project_id="",
            status=result_status,
            objective_value=objective_value,
            solve_time_seconds=solver.WallTime(),
            optimality_gap=solver.BestObjectiveBound() / max(solver.ObjectiveValue(), 1) if solver.ObjectiveValue() > 0 else 0,
            kit_assignments=kit_assignments,
            procurement_plan=procurement_plan,
            inventory_trajectory=inventory_trajectory,
            total_cost_breakdown={
                "procurement": total_procurement,
                "rental": total_rental,
                "handling": total_handling,
                "holding": total_holding,
                "expected_loss": total_loss,
                "total": objective_value,
            },
        )


# ============================================================
# ROLLING HORIZON SOLVER (for large projects)
# ============================================================

class RollingHorizonSolver:
    """Solves large projects by windowed optimization.
    
    1. Fix decisions for already-executed pours
    2. Solve exact MIP for a 4-week lookahead window
    3. Use relaxed estimates for remaining pours
    4. Roll window forward weekly
    """

    def __init__(
        self,
        all_pours: list[Pour],
        components: list[Component],
        initial_inventory: list[InventoryPosition],
        deployed_allocations: list[DeployedAllocation],
        window_weeks: int = 4,
        step_weeks: int = 1,
    ):
        self.all_pours = sorted(all_pours, key=lambda p: p.planned_date)
        self.components = components
        self.initial_inventory = initial_inventory
        self.deployed_allocations = deployed_allocations
        self.window_weeks = window_weeks
        self.step_weeks = step_weeks

    def solve_rolling(self, current_date: date) -> list[OptimizationResult]:
        """Execute rolling-horizon optimization from current_date forward."""
        results = []
        window_start = current_date
        remaining_pours = [p for p in self.all_pours if p.planned_date >= current_date]

        if not remaining_pours:
            logger.info("No future pours to optimize.")
            return results

        project_end = max(p.planned_date for p in remaining_pours)

        while window_start <= project_end:
            window_end = window_start + timedelta(weeks=self.window_weeks)

            # Pours in this window — solve exactly
            window_pours = [p for p in remaining_pours
                            if window_start <= p.planned_date <= window_end]

            if not window_pours:
                window_start += timedelta(weeks=self.step_weeks)
                continue

            logger.info(
                f"Rolling horizon: optimizing {len(window_pours)} pours "
                f"from {window_start} to {window_end}"
            )

            optimizer = FormworkOptimizer(
                pours=window_pours,
                components=self.components,
                initial_inventory=self.initial_inventory,
                deployed_allocations=self.deployed_allocations,
                max_solve_time_seconds=60,  # Tighter budget per window
            )

            result = optimizer.solve()
            results.append(result)

            # Update inventory and deployed state for next window
            # (In production, this would update from the solution)

            window_start += timedelta(weeks=self.step_weeks)

        return results
